version: '3.8'

services:
  # Redis for Celery background tasks
  redis:
    build:
      context: ./infra/redis
      dockerfile: Dockerfile
    container_name: hilabs-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - hilabs-network


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - hilabs-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - MAX_WORKERS=2
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./backend/app/data:/app/data
      - ./backend/app/models:/app/models
      - ./upload:/app/upload
    depends_on:
      - redis
    networks:
      - hilabs-network

volumes:
  redis_data:

networks:
  hilabs-network:
    driver: bridge
